### ISSUE TITLE
New Small Error in Users Freagment...!! Similar Issue, NULL pointer Exception

### ISSUE THREAD

**Issue by varundeva** [KODDevYouTube/ChatAppTutorial#5]
If Anyone Know Kindly Comment Down Here

12-24 23:51:10.230 8311-8311/com.koddev.chatapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.koddev.chatapp, PID: 8311
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.koddev.chatapp.Fragments.UsersFragment$3.onDataChange(UsersFragment.java:122)
        at com.google.android.gms.internal.firebase_database.zzfc.zza(Unknown Source:13)
        at com.google.android.gms.internal.firebase_database.zzgx.zzdr(Unknown Source:2)
        at com.google.android.gms.internal.firebase_database.zzhd.run(Unknown Source:71)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by AllysonYuShiong** [comment]
go into readUsers() method and replace 
if (!user.getId().equals(firebaseUser.getUid())) 
with
if (user!=null && user.getId() != null && !user.getId().equals(firebaseUser.getUid()))

**Comment by FlavianBulancea** [comment]
Thanks. It worked for me, also mention that it has to be done in UserFragment not MainActivity and you need this in ChatFragments as well:  if (user!=null && user.getId() != null && !user.getId().equals(chatlist.getId()))

**Comment by IshuDeve** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.example.fireboxemail.UsersFragment$1.onDataChange(UsersFragment.java:67)
its not working as i have done all off it ....

**Comment by Norman191** [comment]
This project could have been a great one, if the admin finished working on it.
